In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/student_performance_20_students (1).csv')
print('Datasets load successfully')
df

Datasets load successfully

,Student_ID,Name,Python_Marks,NumPy_Marks,Pandas_Marks,Percentage,Attendance_Percent
0,1001,Aarav Sharma,85,78,92,85.00,91
1,1002,Ananya Verma,76,88,81,81.67,86
2,1003,Vivaan Patel,91,84,89,88.00,95
3,1004,Diya Gupta,68,74,79,73.67,82
4,1005,Aditya Singh,55,63,71,63.00,76
5,1006,Isha Jain,94,96,93,94.33,98
6,1007,Arjun Mehta,72,69,77,72.67,88
7,1008,Kavya Joshi,83,91,86,86.67,93
8,1009,Reyansh Yadav,39,45,52,45.33,67
9,1010,Saanvi Mishra,88,82,90,86.67,96
10,1011,Krishna Rao,61,58,64,61.00,79
11,1012,Myra Kapoor,79,85,88,84.00,90
12,1013,Atharv Das,47,52,43,47.33,72
13,1014,Pari Saxena,96,93,97,95.33,99
14,1015,Ishaan Khan,64,71,68,67.67,84
15,1016,Aadhya Nair,82,77,84,81.00,92
16,1017,Rudra Choudhary,33,38,29,33.33,61
17,1018,Sara Thomas,87,89,80,85.33,94
18,1019,Dhruv Malhotra,58,49,62,56.33,75
19,1020,Meera Kulkarni,74,81,76,77.00,87

In [ ]:
print('-------------------Datasets Informations -----------------')
print('1. Datasets shape')
print(df.shape)
print('2. Datasets columns information')
print(df.columns)
print('3. Datasets descriptions')
print(df.info())

-------------------Datasets Informations -----------------
1. Datasets shape
(20, 7)
2. Datasets columns information
Index(['Student_ID', 'Name', 'Python_Marks', 'NumPy_Marks', 'Pandas_Marks',
       'Percentage', 'Attendance_Percent'],
      dtype='object')
3. Datasets descriptions
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_ID          20 non-null     int64
 1   Name                20 non-null     object
 2   Python_Marks        20 non-null     int64
 3   NumPy_Marks         20 non-null     int64
 4   Pandas_Marks        20 non-null     int64
 5   Percentage          20 non-null     float64
 6   Attendance_Percent  20 non-null     int64
dtypes: float64(1), int64(5), object(1)
memory usage: 1.2+ KB
None

In [9]:
print("Missing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

print("\nStudent ID Duplicates:", df["Student_ID"].duplicated().sum())

print("\nInvalid Marks:")
marks_columns = ["Python_Marks", "NumPy_Marks", "Pandas_Marks"]

for col in marks_columns:
    print(col, ":", ((df[col] < 0) | (df[col] > 100)).sum())

print("\nInvalid Attendance Values:",
      ((df["Attendance_Percent"] < 0) |
       (df["Attendance_Percent"] > 100)).sum())

Missing Values:
Student_ID            0
Name                  0
Python_Marks          0
NumPy_Marks           0
Pandas_Marks          0
Percentage            0
Attendance_Percent    0
Department            0
dtype: int64

Duplicate Rows: 0

Student ID Duplicates: 0

Invalid Marks:
Python_Marks : 0
NumPy_Marks : 0
Pandas_Marks : 0

Invalid Attendance Values: 0

In [10]:
df["Percentage"] = (
    df[marks_columns].mean(axis=1)
).round(2)

display(df[["Student_ID", "Name", "Percentage"]])

    Student_ID             Name  Percentage
0         1001     Aarav Sharma       85.00
1         1002     Ananya Verma       81.67
2         1003     Vivaan Patel       88.00
3         1004       Diya Gupta       73.67
4         1005     Aditya Singh       63.00
5         1006        Isha Jain       94.33
6         1007      Arjun Mehta       72.67
7         1008      Kavya Joshi       86.67
8         1009    Reyansh Yadav       45.33
9         1010    Saanvi Mishra       86.67
10        1011      Krishna Rao       61.00
11        1012      Myra Kapoor       84.00
12        1013       Atharv Das       47.33
13        1014      Pari Saxena       95.33
14        1015      Ishaan Khan       67.67
15        1016      Aadhya Nair       81.00
16        1017  Rudra Choudhary       33.33
17        1018      Sara Thomas       85.33
18        1019   Dhruv Malhotra       56.33
19        1020   Meera Kulkarni       77.00

In [11]:
def calculate_grade(percentage):
    if percentage >= 90:
        return "A+"
    elif percentage >= 80:
        return "A"
    elif percentage >= 70:
        return "B"
    elif percentage >= 60:
        return "C"
    elif percentage >= 40:
        return "D"
    else:
        return "F"

df["Grade"] = df["Percentage"].apply(calculate_grade)

display(df[["Student_ID", "Name", "Percentage", "Grade"]])

    Student_ID             Name  Percentage Grade
0         1001     Aarav Sharma       85.00     A
1         1002     Ananya Verma       81.67     A
2         1003     Vivaan Patel       88.00     A
3         1004       Diya Gupta       73.67     B
4         1005     Aditya Singh       63.00     C
5         1006        Isha Jain       94.33    A+
6         1007      Arjun Mehta       72.67     B
7         1008      Kavya Joshi       86.67     A
8         1009    Reyansh Yadav       45.33     D
9         1010    Saanvi Mishra       86.67     A
10        1011      Krishna Rao       61.00     C
11        1012      Myra Kapoor       84.00     A
12        1013       Atharv Das       47.33     D
13        1014      Pari Saxena       95.33    A+
14        1015      Ishaan Khan       67.67     C
15        1016      Aadhya Nair       81.00     A
16        1017  Rudra Choudhary       33.33     F
17        1018      Sara Thomas       85.33     A
18        1019   Dhruv Malhotra       56.33     D
19        1020   Meera Kulkarni       77.00     B

In [12]:
df["Result"] = np.where(
    (df[marks_columns] >= 33).all(axis=1),
    "Pass",
    "Fail"
)

display(df[[
    "Student_ID", "Name",
    "Python_Marks", "NumPy_Marks", "Pandas_Marks",
    "Percentage", "Grade", "Result"
]])

print("Total Passed:", (df["Result"] == "Pass").sum())
print("Total Failed:", (df["Result"] == "Fail").sum())

,Student_ID,Name,Python_Marks,NumPy_Marks,Pandas_Marks,Percentage,Grade,Result
0,1001,Aarav Sharma,85,78,92,85.00,A,Pass
1,1002,Ananya Verma,76,88,81,81.67,A,Pass
2,1003,Vivaan Patel,91,84,89,88.00,A,Pass
3,1004,Diya Gupta,68,74,79,73.67,B,Pass
4,1005,Aditya Singh,55,63,71,63.00,C,Pass
5,1006,Isha Jain,94,96,93,94.33,A+,Pass
6,1007,Arjun Mehta,72,69,77,72.67,B,Pass
7,1008,Kavya Joshi,83,91,86,86.67,A,Pass
8,1009,Reyansh Yadav,39,45,52,45.33,D,Pass
9,1010,Saanvi Mishra,88,82,90,86.67,A,Pass
10,1011,Krishna Rao,61,58,64,61.00,C,Pass
11,1012,Myra Kapoor,79,85,88,84.00,A,Pass
12,1013,Atharv Das,47,52,43,47.33,D,Pass
13,1014,Pari Saxena,96,93,97,95.33,A+,Pass
14,1015,Ishaan Khan,64,71,68,67.67,C,Pass
15,1016,Aadhya Nair,82,77,84,81.00,A,Pass
16,1017,Rudra Choudhary,33,38,29,33.33,F,Fail
17,1018,Sara Thomas,87,89,80,85.33,A,Pass
18,1019,Dhruv Malhotra,58,49,62,56.33,D,Pass
19,1020,Meera Kulkarni,74,81,76,77.00,B,Pass

Total Passed: 19
Total Failed: 1

In [13]:
print("CLASS PERFORMANCE SUMMARY")
print("-------------------------")

print("Total Students:", len(df))
print("Class Average Percentage:", round(df["Percentage"].mean(), 2))
print("Highest Percentage:", df["Percentage"].max())
print("Lowest Percentage:", df["Percentage"].min())
print("Passed Students:", (df["Result"] == "Pass").sum())
print("Failed Students:", (df["Result"] == "Fail").sum())

CLASS PERFORMANCE SUMMARY
-------------------------
Total Students: 20
Class Average Percentage: 73.27
Highest Percentage: 95.33
Lowest Percentage: 33.33
Passed Students: 19
Failed Students: 1

In [14]:
subject_averages = df[marks_columns].mean().round(2)

print("Subject-wise Average Marks:")
display(subject_averages.to_frame(name="Average_Marks"))

best_subject = subject_averages.idxmax()
lowest_subject = subject_averages.idxmin()

print("Best Performing Subject:", best_subject)
print("Lowest Performing Subject:", lowest_subject)

Subject-wise Average Marks:

              Average_Marks
Python_Marks          71.60
NumPy_Marks           73.15
Pandas_Marks          75.05

Best Performing Subject: Pandas_Marks
Lowest Performing Subject: Python_Marks

In [15]:
top_students = df.sort_values(
    by="Percentage",
    ascending=False
).head(3)

print("TOP 3 STUDENTS")
display(top_students[[
    "Student_ID", "Name", "Percentage", "Grade", "Result"
]])

TOP 3 STUDENTS

    Student_ID          Name  Percentage Grade Result
13        1014   Pari Saxena       95.33    A+   Pass
5         1006     Isha Jain       94.33    A+   Pass
2         1003  Vivaan Patel       88.00     A   Pass

In [16]:
low_attendance = df[df["Attendance_Percent"] < 75]

print("Students with Attendance Below 75%:")
display(low_attendance[[
    "Student_ID", "Name", "Attendance_Percent"
]])

print("Low Attendance Students:", len(low_attendance))
print(
    "Class Average Attendance:",
    round(df["Attendance_Percent"].mean(), 2), "%"
)

Students with Attendance Below 75%:

    Student_ID             Name  Attendance_Percent
8         1009    Reyansh Yadav                  67
12        1013       Atharv Das                  72
16        1017  Rudra Choudhary                  61

Low Attendance Students: 3
Class Average Attendance: 85.25 %

In [19]:
print("=" * 45)
print(" STUDENT PERFORMANCE ANALYTICS SYSTEM")
print("=" * 45)

print("Total Students       :", len(df))
print("Class Average        :", round(df["Percentage"].mean(), 2), "%")
print("Highest Percentage   :", round(df["Percentage"].max(), 2), "%")
print("Lowest Percentage    :", round(df["Percentage"].min(), 2), "%")
print("Passed Students      :", (df["Result"] == "Pass").sum())
print("Failed Students      :", (df["Result"] == "Fail").sum())
print("Top Performer        :", df.loc[df["Percentage"].idxmax(), "Name"])
print("Best Subject         :", subject_averages.idxmax())
print("=" * 45)
print("Project completed successfully!")

=============================================
 STUDENT PERFORMANCE ANALYTICS SYSTEM
=============================================
Total Students       : 20
Class Average        : 73.27 %
Highest Percentage   : 95.33 %
Lowest Percentage    : 33.33 %
Passed Students      : 19
Failed Students      : 1
Top Performer        : Pari Saxena
Best Subject         : Pandas_Marks
=============================================
Project completed successfully!